title: "Sajeevan Lab"
description: "Computational and AI-Driven Molecular Science"
logo: /assets/images/lab-logo.png

theme: jekyll-theme-minimal

author:
  name: "Dr. Karuna Anna Sajeevan"
  affiliation: "Srinivasa Ramanujan Institute for Basic Sciences"
